-- MySQL Script generated by MySQL Workbench
-- Tue Jul  7 16:33:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fmalc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fmalc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fmalc` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fmalc` ;

-- -----------------------------------------------------
-- Table `fmalc`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`account` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `is_active` BIT(1) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `role_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_gex1lmaqpg0ir5g1f5eftyaa1` (`username` ASC) VISIBLE,
  INDEX `FKd4vb66o896tay3yy52oqxr9w0` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKd4vb66o896tay3yy52oqxr9w0`
    FOREIGN KEY (`role_id`)
    REFERENCES `fmalc`.`role` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`vehicle` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `average_fuel` DOUBLE NOT NULL,
  `date_of_manufacture` DATE NOT NULL,
  `driver_license` INT(11) NOT NULL,
  `kilometer_running` INT(11) NOT NULL,
  `license_plates` VARCHAR(255) NOT NULL,
  `maximum_capacity` DOUBLE NOT NULL,
  `status` INT(11) NOT NULL,
  `vehicle_name` VARCHAR(255) NOT NULL,
  `weight` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_bft8ds3fdkk56rghb77fnyg1v` (`license_plates` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`fleet_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`fleet_manager` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `identity_no` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(255) NOT NULL,
  `account_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK54bxyg99j7xwen5dq5fcldnem` (`account_id` ASC) VISIBLE,
  CONSTRAINT `FK54bxyg99j7xwen5dq5fcldnem`
    FOREIGN KEY (`account_id`)
    REFERENCES `fmalc`.`account` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`driver` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_of_birth` DATE NOT NULL,
  `driver_license` INT(11) NOT NULL,
  `identity_no` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `license_expires` DATE NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `no` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(255) NOT NULL,
  `status` INT(11) NOT NULL,
  `working_hour` FLOAT NULL DEFAULT NULL,
  `account_id` INT(11) NOT NULL,
  `fleet_manager_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKjadmq2tv9b60y5p0wfy16w9it` (`account_id` ASC) VISIBLE,
  INDEX `FKkp2fbic2m55upbj3lnmui0li8` (`fleet_manager_id` ASC) VISIBLE,
  CONSTRAINT `FKjadmq2tv9b60y5p0wfy16w9it`
    FOREIGN KEY (`account_id`)
    REFERENCES `fmalc`.`account` (`id`),
  CONSTRAINT `FKkp2fbic2m55upbj3lnmui0li8`
    FOREIGN KEY (`fleet_manager_id`)
    REFERENCES `fmalc`.`fleet_manager` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`alert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`alert` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `level` INT(11) NOT NULL,
  `status` BIT(1) NOT NULL,
  `time` DATETIME(6) NOT NULL,
  `driver_id` INT(11) NOT NULL,
  `vehicle_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKqk387ajf1m7tm5kcutlh6fxkl` (`driver_id` ASC) VISIBLE,
  INDEX `FKm7c2d4cxe1uopwr6njxp5k1f8` (`vehicle_id` ASC) VISIBLE,
  CONSTRAINT `FKm7c2d4cxe1uopwr6njxp5k1f8`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `fmalc`.`vehicle` (`id`),
  CONSTRAINT `FKqk387ajf1m7tm5kcutlh6fxkl`
    FOREIGN KEY (`driver_id`)
    REFERENCES `fmalc`.`driver` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`consignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`consignment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `amount` INT(11) NOT NULL,
  `owner_name` VARCHAR(255) NOT NULL,
  `owner_note` VARCHAR(255) NULL DEFAULT NULL,
  `status` INT(11) NOT NULL,
  `weight` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`consignment_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`consignment_history` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  `time` DATE NOT NULL,
  `consignment_id` INT(11) NOT NULL,
  `fleet_manager_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK7un2dbefb101im4cxfl4q3jbr` (`consignment_id` ASC) VISIBLE,
  INDEX `FK93viguflthjfaqmhxisxyviab` (`fleet_manager_id` ASC) VISIBLE,
  CONSTRAINT `FK7un2dbefb101im4cxfl4q3jbr`
    FOREIGN KEY (`consignment_id`)
    REFERENCES `fmalc`.`consignment` (`id`),
  CONSTRAINT `FK93viguflthjfaqmhxisxyviab`
    FOREIGN KEY (`fleet_manager_id`)
    REFERENCES `fmalc`.`fleet_manager` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`day_off`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`day_off` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `end_day` DATETIME(6) NOT NULL,
  `start_day` DATETIME(6) NOT NULL,
  `driver_id` INT(11) NOT NULL,
  `fleet_manager_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKjhcsd8ujun2885gu81adpsdhf` (`driver_id` ASC) VISIBLE,
  INDEX `FK78a9iphdyv6h5ni46a7tlfxnw` (`fleet_manager_id` ASC) VISIBLE,
  CONSTRAINT `FK78a9iphdyv6h5ni46a7tlfxnw`
    FOREIGN KEY (`fleet_manager_id`)
    REFERENCES `fmalc`.`fleet_manager` (`id`),
  CONSTRAINT `FKjhcsd8ujun2885gu81adpsdhf`
    FOREIGN KEY (`driver_id`)
    REFERENCES `fmalc`.`driver` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`fuel_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`fuel_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `current_price` DOUBLE NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`fuel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`fuel` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `filling_date` DATE NOT NULL,
  `km_old` INT(11) NOT NULL,
  `unit_price_at_filling_time` DOUBLE NOT NULL,
  `volume` DOUBLE NOT NULL,
  `fuel_type_id` INT(11) NOT NULL,
  `vehicle_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKh5kakrsd8cwabdn8asusx2p8n` (`fuel_type_id` ASC) VISIBLE,
  INDEX `FKcsj8bx4ew5bbufbsh3ad5hpx6` (`vehicle_id` ASC) VISIBLE,
  CONSTRAINT `FKcsj8bx4ew5bbufbsh3ad5hpx6`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `fmalc`.`vehicle` (`id`),
  CONSTRAINT `FKh5kakrsd8cwabdn8asusx2p8n`
    FOREIGN KEY (`fuel_type_id`)
    REFERENCES `fmalc`.`fuel_type` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`inspection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`inspection` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `inspection_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_hbn4iokseogcve4w41vdtj3bv` (`inspection_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`location` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `time` DATETIME(6) NOT NULL,
  `consignment_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK10xvvrodkjw5863sfk6e2r37l` (`consignment_id` ASC) VISIBLE,
  CONSTRAINT `FK10xvvrodkjw5863sfk6e2r37l`
    FOREIGN KEY (`consignment_id`)
    REFERENCES `fmalc`.`consignment` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`maintain_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`maintain_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `kilometers_number` INT(11) NOT NULL,
  `maintain_type_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`maintenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`maintenance` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `actual_maintain_date` DATE NULL DEFAULT NULL,
  `image_maintain` VARCHAR(255) NOT NULL,
  `km_old` INT(11) NOT NULL,
  `planned_maintain_date` DATE NOT NULL,
  `driver_id` INT(11) NOT NULL,
  `maintain_type_id` INT(11) NOT NULL,
  `vehicle_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKdovlmvrq34jei6sq558dgqd9h` (`driver_id` ASC) VISIBLE,
  INDEX `FK4plhblq97ud7dinmio5lvlbs` (`maintain_type_id` ASC) VISIBLE,
  INDEX `FK1uctvvn1p1y3rp57tq34mao9h` (`vehicle_id` ASC) VISIBLE,
  CONSTRAINT `FK1uctvvn1p1y3rp57tq34mao9h`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `fmalc`.`vehicle` (`id`),
  CONSTRAINT `FK4plhblq97ud7dinmio5lvlbs`
    FOREIGN KEY (`maintain_type_id`)
    REFERENCES `fmalc`.`maintain_type` (`id`),
  CONSTRAINT `FKdovlmvrq34jei6sq558dgqd9h`
    FOREIGN KEY (`driver_id`)
    REFERENCES `fmalc`.`driver` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`notification` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `status` BIT(1) NOT NULL,
  `time` DATETIME(6) NOT NULL,
  `driver_id` INT(11) NOT NULL,
  `vehicle_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKn2xfgfgrnl177v2p9ca2odk2o` (`driver_id` ASC) VISIBLE,
  INDEX `FKfv99ej3rl460ak0erv34yk7vd` (`vehicle_id` ASC) VISIBLE,
  CONSTRAINT `FKfv99ej3rl460ak0erv34yk7vd`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `fmalc`.`vehicle` (`id`),
  CONSTRAINT `FKn2xfgfgrnl177v2p9ca2odk2o`
    FOREIGN KEY (`driver_id`)
    REFERENCES `fmalc`.`driver` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`place` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `actual_time` DATETIME(6) NULL DEFAULT NULL,
  `address` VARCHAR(255) NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `planned_time` DATETIME(6) NOT NULL,
  `priority` INT(11) NOT NULL,
  `type` INT(11) NOT NULL,
  `consignment_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK202l4yhf2qrxcptqcdy8pc6rx` (`consignment_id` ASC) VISIBLE,
  CONSTRAINT `FK202l4yhf2qrxcptqcdy8pc6rx`
    FOREIGN KEY (`consignment_id`)
    REFERENCES `fmalc`.`consignment` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`report_issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`report_issue` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `create_time` DATETIME(6) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `status` BIT(1) NULL DEFAULT NULL,
  `update_time` DATETIME(6) NOT NULL,
  `create_by` INT(11) NOT NULL,
  `inspection_id` INT(11) NOT NULL,
  `update_by` INT(11) NOT NULL,
  `vehicle_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKg1wd5f86v5wcy2f1jh9kj148y` (`create_by` ASC) VISIBLE,
  INDEX `FK4kahp60iq5kenmd1qhb0ry7qs` (`inspection_id` ASC) VISIBLE,
  INDEX `FKoeqhwgd3l2sjjqwjpafcdl2n9` (`update_by` ASC) VISIBLE,
  INDEX `FK5qaqj68iv6peccwu8j1atfg16` (`vehicle_id` ASC) VISIBLE,
  CONSTRAINT `FK4kahp60iq5kenmd1qhb0ry7qs`
    FOREIGN KEY (`inspection_id`)
    REFERENCES `fmalc`.`inspection` (`id`),
  CONSTRAINT `FK5qaqj68iv6peccwu8j1atfg16`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `fmalc`.`vehicle` (`id`),
  CONSTRAINT `FKg1wd5f86v5wcy2f1jh9kj148y`
    FOREIGN KEY (`create_by`)
    REFERENCES `fmalc`.`driver` (`id`),
  CONSTRAINT `FKoeqhwgd3l2sjjqwjpafcdl2n9`
    FOREIGN KEY (`update_by`)
    REFERENCES `fmalc`.`driver` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`schedule` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `image_consignment` VARCHAR(255) NULL DEFAULT NULL,
  `is_approve` BIT(1) NULL DEFAULT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  `consignment_id` INT(11) NOT NULL,
  `driver_id` INT(11) NOT NULL,
  `vehicle_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKihr8fcsx7b2mygrjsh0bapdhj` (`consignment_id` ASC) VISIBLE,
  INDEX `FKmjfuvpp6n6ce63ppi9j3xnntr` (`driver_id` ASC) VISIBLE,
  INDEX `FK5s6sphay5edjq73mnw5gxwwaa` (`vehicle_id` ASC) VISIBLE,
  CONSTRAINT `FK5s6sphay5edjq73mnw5gxwwaa`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `fmalc`.`vehicle` (`id`),
  CONSTRAINT `FKihr8fcsx7b2mygrjsh0bapdhj`
    FOREIGN KEY (`consignment_id`)
    REFERENCES `fmalc`.`consignment` (`id`),
  CONSTRAINT `FKmjfuvpp6n6ce63ppi9j3xnntr`
    FOREIGN KEY (`driver_id`)
    REFERENCES `fmalc`.`driver` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
