-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 23:43:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fmalc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fmalc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fmalc` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fmalc` ;

-- -----------------------------------------------------
-- Table `fmalc`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`account` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `role` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `account_id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`license_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`license_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `license_type_name` VARCHAR(10) NOT NULL,
  `usage_limit` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `type_id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`driver_license`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`driver_license` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `license_type_id` INT(11) NOT NULL,
  `no` VARCHAR(20) NOT NULL,
  `expires` DOUBLE NOT NULL,
  `beginning_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `driver_license_id` (`id` ASC) VISIBLE,
  INDEX `license_type_id` (`license_type_id` ASC) VISIBLE,
  CONSTRAINT `driver_license_ibfk_1`
    FOREIGN KEY (`license_type_id`)
    REFERENCES `fmalc`.`license_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`driver` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `identity_no` VARCHAR(12) NOT NULL,
  `number_phone` VARCHAR(11) NOT NULL,
  `name` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `account_id` INT(11) NOT NULL,
  `driver_license_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `driver_id` (`id` ASC) VISIBLE,
  INDEX `account_id` (`account_id` ASC) VISIBLE,
  INDEX `driver_license_fk_idx` (`driver_license_id` ASC) VISIBLE,
  CONSTRAINT `driver_ibfk_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `fmalc`.`account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `driver_license_fk`
    FOREIGN KEY (`driver_license_id`)
    REFERENCES `fmalc`.`driver_license` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`alert_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`alert_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `alert_type_name` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `alert_type_id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`vehicle_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`vehicle_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `vehicle_type_name` VARCHAR(250) NOT NULL,
  `maximum_capacity` DOUBLE NOT NULL,
  `average_fuel` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `vehicle_type_id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`vehicle` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `license_plates` VARCHAR(50) NOT NULL COMMENT 'Biển số xe',
  `vehicle_type_id` INT(11) NOT NULL,
  `date_of_manufacture` DATE NOT NULL,
  `kilometer_running` INT(11) NOT NULL,
  `current_location` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `vehicle_id` (`id` ASC) VISIBLE,
  INDEX `vehicle_type_id` (`vehicle_type_id` ASC) VISIBLE,
  CONSTRAINT `vehicle_ibfk_2`
    FOREIGN KEY (`vehicle_type_id`)
    REFERENCES `fmalc`.`vehicle_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`alert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`alert` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `vehicle_id` INT(11) NOT NULL,
  `time` DATETIME NOT NULL,
  `content` VARCHAR(250) NOT NULL,
  `alert_type_id` INT(11) NOT NULL,
  `driver_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `alert_id` (`id` ASC) VISIBLE,
  INDEX `alert_type_id` (`alert_type_id` ASC) VISIBLE,
  INDEX `vehicle_id` (`vehicle_id` ASC) VISIBLE,
  INDEX `alert_driver_fk_idx` (`driver_id` ASC) VISIBLE,
  CONSTRAINT `alert_driver_fk`
    FOREIGN KEY (`driver_id`)
    REFERENCES `fmalc`.`driver` (`id`),
  CONSTRAINT `alert_ibfk_1`
    FOREIGN KEY (`alert_type_id`)
    REFERENCES `fmalc`.`alert_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `alert_vehicle_fk`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `fmalc`.`vehicle` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`consignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`consignment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_name` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `weight` DOUBLE NOT NULL,
  `amount` INT(11) NOT NULL,
  `owner_note` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `owner_reason_note` VARCHAR(250) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'Lí do khách hàng hủy, trì hoãn đơn hàng',
  PRIMARY KEY (`id`),
  INDEX `consignment_id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`consignment_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`consignment_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `consignment_status_name` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `consignment_status_id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`consignment_status_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`consignment_status_detail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_consignment` INT(11) NOT NULL,
  `id_status` INT(11) NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_CSD_consignment_idx` (`id_consignment` ASC) VISIBLE,
  INDEX `FK_CSD_status_idx` (`id_status` ASC) VISIBLE,
  CONSTRAINT `FK_CSD_consignment`
    FOREIGN KEY (`id_consignment`)
    REFERENCES `fmalc`.`consignment` (`id`),
  CONSTRAINT `FK_CSD_status`
    FOREIGN KEY (`id_status`)
    REFERENCES `fmalc`.`consignment_status` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`delivery` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `place_of_delivery` VARCHAR(250) NULL DEFAULT NULL,
  `delivery_time` DATETIME NULL DEFAULT NULL,
  `longitude` VARCHAR(45) NULL DEFAULT NULL,
  `latitude` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `delivery_id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`receipt` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `place_of_receipt` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL,
  `longitude` VARCHAR(45) NOT NULL,
  `latitude` VARCHAR(45) NOT NULL,
  `time_receipt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`delivery_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`delivery_detail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_receipt` INT(11) NOT NULL,
  `id_delivery` INT(11) NOT NULL,
  `id_consignment` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_details_delivery_idx` (`id_delivery` ASC) VISIBLE,
  INDEX `FK_details_receipt_idx` (`id_receipt` ASC) VISIBLE,
  INDEX `FK_details_consignment_idx` (`id_consignment` ASC) VISIBLE,
  CONSTRAINT `consignment_detail_fk`
    FOREIGN KEY (`id_consignment`)
    REFERENCES `fmalc`.`consignment` (`id`),
  CONSTRAINT `delivery_detail_fk`
    FOREIGN KEY (`id_delivery`)
    REFERENCES `fmalc`.`delivery` (`id`),
  CONSTRAINT `receipt_detail_fk`
    FOREIGN KEY (`id_receipt`)
    REFERENCES `fmalc`.`receipt` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`driver_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`driver_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `driver_status_id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`driver_status_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`driver_status_detail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_status` INT(11) NOT NULL,
  `id_driver` INT(11) NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_details_driver_idx` (`id_driver` ASC) VISIBLE,
  INDEX `FK_details_status_idx` (`id_status` ASC) VISIBLE,
  CONSTRAINT `driver_fk`
    FOREIGN KEY (`id_driver`)
    REFERENCES `fmalc`.`driver` (`id`),
  CONSTRAINT `status_fk`
    FOREIGN KEY (`id_status`)
    REFERENCES `fmalc`.`driver_status` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fmalc`.`inspection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`inspection` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `inspection_name` VARCHAR(250) NOT NULL,
  `inspection_level` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `inspection_id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`location` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `latitude` VARCHAR(250) NOT NULL,
  `longitude` VARCHAR(250) NOT NULL,
  `time` DATETIME NOT NULL COMMENT 'Thời gian khi xe dừng tại 1 điểm',
  `vehicle_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `location_id` (`id` ASC) VISIBLE,
  INDEX `vehicle_id` (`vehicle_id` ASC) VISIBLE,
  CONSTRAINT `location_ibfk_1`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `fmalc`.`vehicle` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`maintain_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`maintain_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `maintain_type_name` VARCHAR(250) NOT NULL,
  `kilometers_number` INT(11) NOT NULL,
  `content` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `maintain_type_id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`maintain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`maintain` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `vehicle_id` INT(11) NOT NULL,
  `maintain_type_id` INT(11) NOT NULL,
  `maintain_date` DATE NOT NULL,
  `km_old` INT(11) NOT NULL,
  `km_new` INT(11) NOT NULL,
  `image_maintain` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `maintain_id` (`id` ASC) VISIBLE,
  INDEX `vehicle_id` (`vehicle_id` ASC) VISIBLE,
  INDEX `maintain_type_id` (`maintain_type_id` ASC) VISIBLE,
  CONSTRAINT `maintain_ibfk_1`
    FOREIGN KEY (`maintain_type_id`)
    REFERENCES `fmalc`.`maintain_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `vehicle_maintain_fk`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `fmalc`.`vehicle` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`notify_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`notify_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `notify_type_name` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `notify_type_id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`notify`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`notify` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `vehicle_id` INT(11) NOT NULL,
  `time` DATETIME NOT NULL COMMENT 'Thời gian gửi thông báo',
  `content` VARCHAR(250) NOT NULL,
  `notify_type_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `notify_id` (`id` ASC) VISIBLE,
  INDEX `notify_type_id` (`notify_type_id` ASC) VISIBLE,
  INDEX `vehicle_id` (`vehicle_id` ASC) VISIBLE,
  INDEX `notify_type_id_2` (`notify_type_id` ASC) VISIBLE,
  CONSTRAINT `notify_type_ibfk_1`
    FOREIGN KEY (`notify_type_id`)
    REFERENCES `fmalc`.`notify_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `notify_vehicle_fk`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `fmalc`.`vehicle` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`report_issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`report_issue` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `vehicle_id` INT(11) NOT NULL,
  `inspection_id` INT(11) NOT NULL,
  `time` DATETIME NOT NULL,
  `driver_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `vehicle_issue_fk_idx` (`vehicle_id` ASC) VISIBLE,
  INDEX `inspection_report_fk_idx` (`inspection_id` ASC) VISIBLE,
  INDEX `driver_issue_fk_idx` (`driver_id` ASC) VISIBLE,
  CONSTRAINT `driver_issue_fk`
    FOREIGN KEY (`driver_id`)
    REFERENCES `fmalc`.`driver` (`id`),
  CONSTRAINT `inspection_report_fk`
    FOREIGN KEY (`inspection_id`)
    REFERENCES `fmalc`.`inspection` (`id`),
  CONSTRAINT `vehicle_issue_fk`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `fmalc`.`vehicle` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`schedule` (
  `driver_id` INT(11) NOT NULL,
  `vehicle_id` INT(11) NOT NULL,
  `drive_date` DATE NOT NULL,
  `consignment_id` INT(11) NOT NULL,
  `image_consignment` VARCHAR(300) NOT NULL,
  `note` VARCHAR(250) NULL DEFAULT NULL COMMENT 'Lý do cancel',
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `driver_id` (`driver_id` ASC) VISIBLE,
  INDEX `vehicle_id` (`vehicle_id` ASC) VISIBLE,
  INDEX `consignemnt_id` (`consignment_id` ASC) VISIBLE,
  CONSTRAINT `schedule_ibfk_1`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `fmalc`.`vehicle` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `schedule_ibfk_2`
    FOREIGN KEY (`driver_id`)
    REFERENCES `fmalc`.`driver` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `schedule_ibfk_3`
    FOREIGN KEY (`consignment_id`)
    REFERENCES `fmalc`.`consignment` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`vehicle_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`vehicle_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `vehicle_status_name` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `vehicle_status_id` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fmalc`.`vehicle_status_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fmalc`.`vehicle_status_detail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_vehicle` INT(11) NOT NULL,
  `id_status` INT(11) NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_details_vehicle_idx` (`id_vehicle` ASC) VISIBLE,
  INDEX `FK_details_status_idx` (`id_status` ASC) VISIBLE,
  CONSTRAINT `FK_details_status_vehicle`
    FOREIGN KEY (`id_status`)
    REFERENCES `fmalc`.`vehicle_status` (`id`),
  CONSTRAINT `FK_details_vehicle`
    FOREIGN KEY (`id_vehicle`)
    REFERENCES `fmalc`.`vehicle` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
